### ISSUE TITLE
Error: "open_on_weekends" doesn't stay true

### ISSUE THREAD

**Issue by esau-morais** [EliasGcf/nlw-3#1]
### Expected behavior

`open_on_weekends` needs to be boolean

### Actual behavior

`open_on_weekends` is boolean, but it's not receiving `true`

### Solution

1. Go to the [orphanage controller](https://github.com/EliasGcf/nlw-3/blob/master/backend/src/controllers/OrphanagesController.ts)

2. Edit the [line number 60](https://github.com/EliasGcf/nlw-3/blob/master/backend/src/controllers/OrphanagesController.ts#L60)

3. Instead, you just need to pass the `open_on_weekends`

```
...
open_on_weekends,
...
```

### Solution #2

Follow the steps in the 3rd video

**Comment by EliasGcf** [comment]
Hey, @esau-morais !

The application uses Multipart Form to receive the data with images.

So, `open_on_weeknds` is a string with `'true'` or `'false'` value. Because of that, the code:
```
...
open_on_weekends: open_on_weekends === 'true',
....
```
Is right.

Thank you for create this issue!!

**Comment by esau-morais** [comment]
> Hey, @esau-morais !
> 
> The application uses Multipart Form to receive the data with images.
> 
> So, `open_on_weeknds` is a string with `'true'` or `'false'` value. Because of that, the code:
> 
> ```
> ...
> open_on_weekends: open_on_weekends === 'true',
> ....
> ```
> 
> Is right.
> 
> Thank you for create this issue!!

Oh, okay. Now it makes sense why was not working. Thank you for noticing.
